version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=bike_rental
      - DB_USER=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: bike_rental
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
